#!/usr/bin/env python3
import zlib
import struct
import argparse

parser = argparse.ArgumentParser(prog="create_sbl")
parser.add_argument("input")
parser.add_argument("output")
args = parser.parse_args()

with open(args.input, mode="rb") as file:
    data = file.read()
    size = len(data)
    version = 0x01010101
    checksum = zlib.crc32(data)
    payload = struct.pack(
        f"<2s4x2s28xII2s2xI28x{size}s",
        b"\x40\x02",
        b"\x20\x00",
        version,
        size,
        b"\x00\x04",
        checksum,
        data,
    )

with open(args.output, "xb") as file:
    file.write(payload)
