#!/usr/bin/env python3
# ref https://github.com/starfive-tech/Tools/issues/1
import zlib
import struct
import argparse

parser = argparse.ArgumentParser(prog="create_sbl")
parser.add_argument("input")
parser.add_argument("output")
args = parser.parse_args()

with open(args.input, mode="rb") as file:
    data = file.read()
    size = len(data)
    checksum = zlib.crc32(data)
    payload = struct.pack(
        f"<2s2xI28xII2s2xI28x{size}s",
        b"\x40\x02",
        0x200000, # SBL_BAK_OFFSET
        0x01010001, # SBL_VER
        size,
        b"\x00\x04",
        checksum,
        data,
    )

with open(args.output, "xb") as file:
    file.write(payload)
